package store.views;

import store.models.ModelFornecedor;
import store.models.ModelProduto;
import store.models.ModelCliente;
import store.models.ModelVenda;
import store.daos.DAOProduto;
import store.daos.DAOFornecedor;
import store.daos.DAOCliente;
import store.daos.DAOVenda;
import store.common.handlers.HandlerJanela;

/**
 *
 * @author Erick Frederick
 */
public class ViewHome extends javax.swing.JFrame {
    public ViewHome(HandlerJanela injectedHandlerJanela) {
        this._HANDLER_JANELA = injectedHandlerJanela;

        initComponents();
    }

    private final HandlerJanela _HANDLER_JANELA;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMCCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMCFornecedor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMCProduto = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMCVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        jMCCliente.setText("Cliente");
        jMCCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMCCliente);
        jMenu1.add(jSeparator1);

        jMCFornecedor.setText("Fornecedor");
        jMCFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMCFornecedor);
        jMenu1.add(jSeparator2);

        jMCProduto.setText("Produto");
        jMCProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMCProduto);
        jMenu1.add(jSeparator3);

        jMCVenda.setText("Venda");
        jMCVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCVendaActionPerformed(evt);
            }
        });
        jMenu1.add(jMCVenda);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCClienteActionPerformed
        ViewCliente viewCliente = new ViewCliente(
            this._HANDLER_JANELA,
            new ModelCliente(),
            new DAOCliente()
        );

        this._HANDLER_JANELA.configurarJanela(viewCliente);
        this._HANDLER_JANELA.rederizarJanela(viewCliente);
    }//GEN-LAST:event_jMCClienteActionPerformed

    private void jMCFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCFornecedorActionPerformed
        ViewFornecedor viewFornecedor = new ViewFornecedor(
            this._HANDLER_JANELA,
            new ModelFornecedor(),
            new DAOFornecedor()
        );

        this._HANDLER_JANELA.configurarJanela(viewFornecedor);
        this._HANDLER_JANELA.rederizarJanela(viewFornecedor);
    }//GEN-LAST:event_jMCFornecedorActionPerformed

    private void jMCProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCProdutoActionPerformed
        ViewProduto viewProduto = new ViewProduto(
            this._HANDLER_JANELA,
            new ModelProduto(),
            new DAOProduto()
        );

        this._HANDLER_JANELA.configurarJanela(viewProduto);
        this._HANDLER_JANELA.rederizarJanela(viewProduto);
    }//GEN-LAST:event_jMCProdutoActionPerformed

    private void jMCVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCVendaActionPerformed
        ViewVenda viewVenda = new ViewVenda(
            this._HANDLER_JANELA,
            new ModelVenda(),
            new DAOVenda()
        );

        this._HANDLER_JANELA.configurarJanela(viewVenda);
        this._HANDLER_JANELA.rederizarJanela(viewVenda);
    }//GEN-LAST:event_jMCVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMCCliente;
    private javax.swing.JMenuItem jMCFornecedor;
    private javax.swing.JMenuItem jMCProduto;
    private javax.swing.JMenuItem jMCVenda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
