package condominio.views;

import javax.swing.table.DefaultTableModel;

import common.handlers.HandlerJanela;
import common.interfaces.Viewable;
import condominio.models.ModelPedido;
import condominio.daos.DAOPedidos;

/**
 *
 * @author Erick Frederick
 */
public class ViewPedido extends javax.swing.JFrame implements Viewable {
    public ViewPedido(
        HandlerJanela injectedHandlerJanela,
        ModelPedido injectedModel,
        DAOPedidos injectedDao
    ) {
        this._HANDLER_JANELA = injectedHandlerJanela;
        this._MODELO = injectedModel;
        this._DAO = injectedDao;

        initComponents();
        hidrataTabela();
    }

    @Override
    public final void hidrataTabela(){
        DefaultTableModel tabela = (DefaultTableModel) jTabela.getModel();

        tabela.setNumRows(0);

        this._DAO.Listar().forEach((ap) -> {
            tabela.addRow(new Object[]{
                ap.getIdPedido(),
                ap.getNumeroPedido(),
                ap.getIdProduto(),
                ap.getIdCliente(),
                ap.getEndereco(),
                ap.getTotal(),
                ap.getFormaPagamento()
            });
        });
    }

    @Override
    public void limpaCamposDeEntrada() {
        this._HANDLER_JANELA.limparListaDeInput(new javax.swing.JTextField[]{
            jTId,
            jTNumeroPedido,
            jTIdProduto,
            jTIdCliente,
            jTEndereco,
            jTTotal,
            jTFormaPagamento
        });

        jTNumeroPedido.requestFocus();
    }
    
    @Override
    public void atualizaJanela() {
        hidrataTabela();
        limpaCamposDeEntrada();
    }

    @Override
    public void atualizaValoresModelo(Boolean atualizaOId){
        if(atualizaOId) {
            int idPedido = Integer.parseInt(jTId.getText().trim());

            this._MODELO.setIdPedido(idPedido);
        }

        int numeroPedido = Integer.parseInt(jTNumeroPedido.getText().trim());
        int idProduto = Integer.parseInt(jTIdProduto.getText().trim());
        int idCliente = Integer.parseInt(jTIdCliente.getText().trim());
        String endereco = jTEndereco.getText().trim();
        Double total = Double.parseDouble(jTTotal.getText().trim());
        String formaPagamento =  jTFormaPagamento.getText().trim();

        this._MODELO.setNumeroPedido(numeroPedido);
        this._MODELO.setIdProduto(idProduto);
        this._MODELO.setIdCliente(idCliente);
        this._MODELO.setEndereco(endereco);
        this._MODELO.setTotal(total);
        this._MODELO.setFormaPagamento(formaPagamento);
    }
 
    private final HandlerJanela _HANDLER_JANELA;
    private final ModelPedido _MODELO;
    private final DAOPedidos _DAO;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jTId = new javax.swing.JTextField();
        jTIdProduto = new javax.swing.JTextField();
        jLId = new javax.swing.JLabel();
        jLNumeroPedido = new javax.swing.JLabel();
        jLIdProduto = new javax.swing.JLabel();
        jBGravar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBDeletar = new javax.swing.JButton();
        jTNumeroPedido = new javax.swing.JTextField();
        jLIdCliente = new javax.swing.JLabel();
        jTIdCliente = new javax.swing.JTextField();
        jLEndereco = new javax.swing.JLabel();
        jTEndereco = new javax.swing.JTextField();
        jLTotal = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();
        jLFormaPagamento = new javax.swing.JLabel();
        jTFormaPagamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabela.setBackground(new java.awt.Color(207, 207, 207));
        jTabela.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Número do Pedido", "ID do Produto", "ID do Cliente", "Endereço", "Total", "Forma de Pagamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabela.setGridColor(new java.awt.Color(207, 207, 207));
        jTabela.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTabela.setShowHorizontalLines(false);
        jTabela.getTableHeader().setResizingAllowed(false);
        jTabela.getTableHeader().setReorderingAllowed(false);
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabela);
        if (jTabela.getColumnModel().getColumnCount() > 0) {
            jTabela.getColumnModel().getColumn(0).setResizable(false);
            jTabela.getColumnModel().getColumn(1).setResizable(false);
            jTabela.getColumnModel().getColumn(2).setResizable(false);
            jTabela.getColumnModel().getColumn(3).setResizable(false);
            jTabela.getColumnModel().getColumn(4).setResizable(false);
            jTabela.getColumnModel().getColumn(5).setResizable(false);
            jTabela.getColumnModel().getColumn(6).setResizable(false);
        }

        jTId.setEditable(false);
        jTId.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTId.setBorder(null);
        jTId.setFocusable(false);
        jTId.setSelectedTextColor(new java.awt.Color(240, 240, 240));

        jTIdProduto.setBackground(new java.awt.Color(207, 207, 207));
        jTIdProduto.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTIdProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTIdProduto.setBorder(null);

        jLId.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLId.setText("ID");

        jLNumeroPedido.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLNumeroPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNumeroPedido.setText("Número Pedido");

        jLIdProduto.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLIdProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIdProduto.setText("ID do produto");

        jBGravar.setBackground(new java.awt.Color(85, 179, 59));
        jBGravar.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jBGravar.setForeground(new java.awt.Color(232, 232, 232));
        jBGravar.setText("Gravar");
        jBGravar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });

        jBAlterar.setBackground(new java.awt.Color(82, 82, 82));
        jBAlterar.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jBAlterar.setForeground(new java.awt.Color(232, 232, 232));
        jBAlterar.setText("Alterar");
        jBAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBDeletar.setBackground(new java.awt.Color(140, 42, 42));
        jBDeletar.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jBDeletar.setForeground(new java.awt.Color(232, 232, 232));
        jBDeletar.setText("Deletar");
        jBDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeletarActionPerformed(evt);
            }
        });

        jTNumeroPedido.setBackground(new java.awt.Color(207, 207, 207));
        jTNumeroPedido.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTNumeroPedido.setBorder(null);

        jLIdCliente.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLIdCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIdCliente.setText("ID Cliente");

        jTIdCliente.setBackground(new java.awt.Color(207, 207, 207));
        jTIdCliente.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTIdCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTIdCliente.setBorder(null);

        jLEndereco.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEndereco.setText("Endereço");

        jTEndereco.setBackground(new java.awt.Color(207, 207, 207));
        jTEndereco.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTEndereco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTEndereco.setBorder(null);

        jLTotal.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTotal.setText("Total");

        jTTotal.setBackground(new java.awt.Color(207, 207, 207));
        jTTotal.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTTotal.setBorder(null);

        jLFormaPagamento.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLFormaPagamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFormaPagamento.setText("Forma de Pagamento");

        jTFormaPagamento.setBackground(new java.awt.Color(207, 207, 207));
        jTFormaPagamento.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTFormaPagamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFormaPagamento.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLNumeroPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jTNumeroPedido, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTIdProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLIdProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jTIdCliente)
                            .addComponent(jLFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jTFormaPagamento))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLId)
                .addGap(18, 18, 18)
                .addComponent(jTId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumeroPedido)
                    .addComponent(jLIdProduto)
                    .addComponent(jLIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndereco)
                    .addComponent(jLTotal)
                    .addComponent(jLFormaPagamento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed
        atualizaValoresModelo(false);

        this._DAO.Inserir(this._MODELO);

        atualizaJanela();
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        atualizaValoresModelo(true);

        this._DAO.Alterar(this._MODELO);

        atualizaJanela();
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
        this._HANDLER_JANELA.atulizarListaDeInputRelacionadoTabela(new javax.swing.JTextField[]{
            jTId,
            jTNumeroPedido,
            jTIdProduto,
            jTIdCliente,
            jTEndereco,
            jTTotal,
            jTFormaPagamento
        }, jTabela);
    }//GEN-LAST:event_jTabelaMouseClicked

    private void jBDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarActionPerformed
        atualizaValoresModelo(true);

        this._DAO.Deletar(this._MODELO);

        atualizaJanela();
    }//GEN-LAST:event_jBDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBDeletar;
    private javax.swing.JButton jBGravar;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLFormaPagamento;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLIdCliente;
    private javax.swing.JLabel jLIdProduto;
    private javax.swing.JLabel jLNumeroPedido;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTEndereco;
    private javax.swing.JTextField jTFormaPagamento;
    private javax.swing.JTextField jTId;
    private javax.swing.JTextField jTIdCliente;
    private javax.swing.JTextField jTIdProduto;
    private javax.swing.JTextField jTNumeroPedido;
    private javax.swing.JTextField jTTotal;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
}
