package condominio.views;

import net.sf.jasperreports.engine.JasperPrint;

import common.handlers.HandlerJanela;
import common.handlers.HandlerRelatorio;
import common.enums.EnumRelatorios;
import condominio.models.*;
import condominio.daos.*;

/**
 *
 * @author Erick Frederick
 */
public class ViewHome extends javax.swing.JFrame {
    public ViewHome(
        HandlerJanela injectedHandlerJanela,
        HandlerRelatorio injtectedHandlerRelatorio
    ) {
        this._HANDLER_JANELA = injectedHandlerJanela;
        this._HANDLER_RELATORIO = injtectedHandlerRelatorio;

        initComponents();
    }

    private final HandlerJanela _HANDLER_JANELA;
    private final HandlerRelatorio _HANDLER_RELATORIO;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMSClientes = new javax.swing.JMenuItem();
        jMSSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMSPedido = new javax.swing.JMenuItem();
        jMSSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMSProduto = new javax.swing.JMenuItem();
        jMRApartamento = new javax.swing.JMenu();
        jMRClientes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMRPedidos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMRProdutos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Sistema");

        jMSClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/004-ceo.png"))); // NOI18N
        jMSClientes.setText("Clientes");
        jMSClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMSClientes);
        jMenu1.add(jMSSeparator1);

        jMSPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/009-delivery-man.png"))); // NOI18N
        jMSPedido.setText("Pedido");
        jMSPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSPedidoActionPerformed(evt);
            }
        });
        jMenu1.add(jMSPedido);
        jMenu1.add(jMSSeparator2);

        jMSProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/003-burger.png"))); // NOI18N
        jMSProduto.setText("Produtos");
        jMSProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMSProduto);

        jMenuBar1.add(jMenu1);

        jMRApartamento.setText("Relatorios");

        jMRClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/007-customer-service.png"))); // NOI18N
        jMRClientes.setText("Clientes");
        jMRClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRClientesActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRClientes);
        jMRApartamento.add(jSeparator1);

        jMRPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/008-presentation.png"))); // NOI18N
        jMRPedidos.setText("Pedidos");
        jMRPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRPedidosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRPedidos);
        jMRApartamento.add(jSeparator2);

        jMRProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/010-pencil.png"))); // NOI18N
        jMRProdutos.setText("Produtos");
        jMRProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRProdutosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRProdutos);

        jMenuBar1.add(jMRApartamento);

        jMenu3.setText("Sair");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/exit.png"))); // NOI18N
        jMenuItem7.setText("Sair");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMSClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSClientesActionPerformed
        ViewCliente viewCliente = new ViewCliente(
            this._HANDLER_JANELA,
            new ModelCliente(),
            new DAOClientes()
        );

        this._HANDLER_JANELA.configurarJanela(viewCliente);
        this._HANDLER_JANELA.rederizarJanela(viewCliente);
    }//GEN-LAST:event_jMSClientesActionPerformed

    private void jMSPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSPedidoActionPerformed
        ViewPedido viewPedido = new ViewPedido(
            this._HANDLER_JANELA,
            new ModelPedido(),
            new DAOPedidos()
        );

        this._HANDLER_JANELA.configurarJanela(viewPedido);
        this._HANDLER_JANELA.rederizarJanela(viewPedido);
    }//GEN-LAST:event_jMSPedidoActionPerformed

    private void jMSProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSProdutoActionPerformed
        ViewProduto viewProduto = new ViewProduto(
            this._HANDLER_JANELA,
            new ModelProduto(),
            new DAOProdutos()
        );

        this._HANDLER_JANELA.configurarJanela(viewProduto);
        this._HANDLER_JANELA.rederizarJanela(viewProduto);
    }//GEN-LAST:event_jMSProdutoActionPerformed

    private void jMRClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRClientesActionPerformed
        JasperPrint relatorioCliente = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_CLIENTE.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioCliente);
    }//GEN-LAST:event_jMRClientesActionPerformed

    private void jMRPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRPedidosActionPerformed
        JasperPrint relatorioPedido = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_PEDIDO.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioPedido);
    }//GEN-LAST:event_jMRPedidosActionPerformed

    private void jMRProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRProdutosActionPerformed
        JasperPrint relatorioProduto = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_PRODUTO.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioProduto);
    }//GEN-LAST:event_jMRProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMRApartamento;
    private javax.swing.JMenuItem jMRClientes;
    private javax.swing.JMenuItem jMRPedidos;
    private javax.swing.JMenuItem jMRProdutos;
    private javax.swing.JMenuItem jMSClientes;
    private javax.swing.JMenuItem jMSPedido;
    private javax.swing.JMenuItem jMSProduto;
    private javax.swing.JPopupMenu.Separator jMSSeparator1;
    private javax.swing.JPopupMenu.Separator jMSSeparator2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
