package common.handlers;

/**
 *
 * @author Erick Frederick Caldeira
 */
public class HandlerInput {
    public String higienizarData(String data){
        String dataHigienizada = data;
        
        if(this.textoNaoESoEspaco(data)){
           dataHigienizada = data.replaceAll("[//]", "-").replace(" ", "");
        }

        return dataHigienizada;
    }

    public String higienizarCpf(String cpf){
        String cpfHigienizado =  cpf;
        
        if(this.textoNaoESoEspaco(cpf)){
           cpfHigienizado = cpf.replaceAll("[.-]", "".replace(" ", ""));
        }

        return cpfHigienizado;
    }

    public String higienizarTelefone(String telefone){
        String telefoneHigienizado =  telefone;
        
        if(this.textoNaoESoEspaco(telefone)){
            /**TO-DO
             *  Fix inconsistency generated by values that come from the DB with special characters and
             *  JFormattedTextFields.
             */
           telefoneHigienizado = telefone.replaceAll("[()-]", "").replace(" ", "");
        }

        return telefoneHigienizado;
    }

    private boolean textoNaoESoEspaco(String texto){
        return texto.trim().length() > 0;
    }
}
