package condominio.View;

import java.sql.Connection;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

import condominio.Model.ModelAgenda;
import condominio.Model.ModelApartamento;
import condominio.Model.ModelAreaLazer;
import condominio.Model.ModelProprietario;
import condominio.Model.ModelCarro;
import condominio.Controller.conecta;
import condominio.Controller.DAOAgendas;
import condominio.Controller.DAOApartamentos;
import condominio.Controller.DAOAreasLazer;
import condominio.Controller.DAOProprietarios;
import condominio.Controller.DAOCarros;
import common.JanelaHandler;

/**
 *
 * @author Marcelo
 */
public class ViewHome extends javax.swing.JFrame {
    public ViewHome() {
        initComponents();
    }

    private final JanelaHandler _janelaHandler = new JanelaHandler();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMSAgenda = new javax.swing.JMenuItem();
        jMSApartamentos = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMSAreasLazer = new javax.swing.JMenuItem();
        jMSProprietarios = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMSBlocos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMSGaragens = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMSCarros = new javax.swing.JMenuItem();
        jMRApartamento = new javax.swing.JMenu();
        jMRApartamentos = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMRProprietarios = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Sistema");

        jMSAgenda.setText("Agenda");
        jMSAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(jMSAgenda);

        jMSApartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/View/building.png"))); // NOI18N
        jMSApartamentos.setText("Apartamentos");
        jMSApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSApartamentosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSApartamentos);
        jMenu1.add(jSeparator4);

        jMSAreasLazer.setText("Areas de Lazer");
        jMSAreasLazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSAreasLazerActionPerformed(evt);
            }
        });
        jMenu1.add(jMSAreasLazer);

        jMSProprietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/View/prop.png"))); // NOI18N
        jMSProprietarios.setText("Proprietarios");
        jMSProprietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSProrietariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSProprietarios);
        jMenu1.add(jSeparator3);

        jMSBlocos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/View/bloco.png"))); // NOI18N
        jMSBlocos.setText("Blocos");
        jMSBlocos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSBlocosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSBlocos);
        jMenu1.add(jSeparator2);

        jMSGaragens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/View/garage.png"))); // NOI18N
        jMSGaragens.setText("Garagens");
        jMSGaragens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSGaragensActionPerformed(evt);
            }
        });
        jMenu1.add(jMSGaragens);
        jMenu1.add(jSeparator1);

        jMSCarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/View/car.png"))); // NOI18N
        jMSCarros.setText("Veículos");
        jMSCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSCarrosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSCarros);

        jMenuBar1.add(jMenu1);

        jMRApartamento.setText("Relatorios");

        jMRApartamentos.setText("Apartamentos");
        jMRApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRApartamentoActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRApartamentos);
        jMRApartamento.add(jSeparator6);

        jMRProprietarios.setText("Proprietarios");
        jMRProprietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRProprietariosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRProprietarios);
        jMRApartamento.add(jSeparator5);

        jMenuBar1.add(jMRApartamento);

        jMenu3.setText("Sair");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/View/exit.png"))); // NOI18N
        jMenuItem7.setText("Sair");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRApartamentoActionPerformed
        Connection con;
        
        try {
            con = new conecta().getConnection();
            JasperPrint print = JasperFillManager.fillReport("/Users/marcelo/NetBeansProjects/U2S2.2POO2Seg/src/condominio/View/apartamentos.jasper",null,con);
            JasperViewer.viewReport(print,false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuRApartamentoActionPerformed

    private void jMenuSApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSApartamentosActionPerformed
        ViewApartamento viewApartamento = new ViewApartamento(new ModelApartamento(), new DAOApartamentos());

        this._janelaHandler.configurarJanela(viewApartamento);
        this._janelaHandler.rederizarJanela(viewApartamento);
    }//GEN-LAST:event_jMenuSApartamentosActionPerformed

    private void jMSProrietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSProrietariosActionPerformed
        ViewProprietario viewProprietario = new ViewProprietario(new ModelProprietario(), new DAOProprietarios());

        this._janelaHandler.configurarJanela(viewProprietario);
        this._janelaHandler.rederizarJanela(viewProprietario);
    }//GEN-LAST:event_jMSProrietariosActionPerformed

    private void jMenuRProprietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRProprietariosActionPerformed
        Connection con;
        
        try {
            con = new conecta().getConnection();
            JasperPrint print = JasperFillManager.fillReport("/Users/marcelo/NetBeansProjects/U2S2.2POO2Seg/src/condominio/View/proprietario.jasper",null,con);
            JasperViewer.viewReport(print,false);
        } catch (Exception e) {
        }
                
    }//GEN-LAST:event_jMenuRProprietariosActionPerformed

    private void jMSBlocosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSBlocosActionPerformed
        
    }//GEN-LAST:event_jMSBlocosActionPerformed

    private void jMSCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSCarrosActionPerformed
        ViewCarro viewCarro = new ViewCarro(new ModelCarro(), new DAOCarros());

        this._janelaHandler.configurarJanela(viewCarro);
        this._janelaHandler.rederizarJanela(viewCarro);
    }//GEN-LAST:event_jMSCarrosActionPerformed

    private void jMSGaragensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSGaragensActionPerformed
        
    }//GEN-LAST:event_jMSGaragensActionPerformed

    private void jMSAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSAgendaActionPerformed
        ViewAgenda viewAgenda = new ViewAgenda(new ModelAgenda(), new DAOAgendas());

        this._janelaHandler.configurarJanela(viewAgenda);
        this._janelaHandler.rederizarJanela(viewAgenda);
    }//GEN-LAST:event_jMSAgendaActionPerformed

    private void jMSAreasLazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSAreasLazerActionPerformed
        ViewAreaLazer viewAreaLazer = new ViewAreaLazer(new ModelAreaLazer(), new DAOAreasLazer());

        this._janelaHandler.configurarJanela(viewAreaLazer);
        this._janelaHandler.rederizarJanela(viewAreaLazer);
    }//GEN-LAST:event_jMSAreasLazerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMRApartamento;
    private javax.swing.JMenuItem jMRApartamentos;
    private javax.swing.JMenuItem jMRProprietarios;
    private javax.swing.JMenuItem jMSAgenda;
    private javax.swing.JMenuItem jMSApartamentos;
    private javax.swing.JMenuItem jMSAreasLazer;
    private javax.swing.JMenuItem jMSBlocos;
    private javax.swing.JMenuItem jMSCarros;
    private javax.swing.JMenuItem jMSGaragens;
    private javax.swing.JMenuItem jMSProprietarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
