package condominio.views;

import java.io.File;
import java.sql.Connection;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

import common.handlers.HandlerJanela;
import common.handlers.HandlerConexao;
import condominio.models.*;
import condominio.daos.*;

/**
 *
 * @author Marcelo
 */
public class ViewHome extends javax.swing.JFrame {
    public ViewHome() {
        initComponents();
    }

    private JasperPrint gerarRelatorioJasper(String nomeRelatorio){
        try {
            String caminhoRelativoPastaRelatorio = "src/relatorios/";

            Connection con = new HandlerConexao().getConnection();
            File arquivoJasper = new File(caminhoRelativoPastaRelatorio + nomeRelatorio + ".jasper");

            return JasperFillManager.fillReport(arquivoJasper.getAbsolutePath(), null, con);
        } catch (Exception e) { }

        return null;
    }

    private final HandlerJanela _handlerJanela = new HandlerJanela();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMSAgenda = new javax.swing.JMenuItem();
        jMSSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMSApartamentos = new javax.swing.JMenuItem();
        jMSSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMSAreasLazer = new javax.swing.JMenuItem();
        jMSSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMSBlocos = new javax.swing.JMenuItem();
        jMSSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMSCorreios = new javax.swing.JMenuItem();
        jMSSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMSFuncionarios = new javax.swing.JMenuItem();
        jMSSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMSGaragens = new javax.swing.JMenuItem();
        jMSSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMSMoradores = new javax.swing.JMenuItem();
        jMSSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMSProprietarios = new javax.swing.JMenuItem();
        jMSSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMSServicos = new javax.swing.JMenuItem();
        jMSSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMSCarros = new javax.swing.JMenuItem();
        jMSSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMSTorres = new javax.swing.JMenuItem();
        jMRApartamento = new javax.swing.JMenu();
        jMRApartamentos = new javax.swing.JMenuItem();
        jMRSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMRProprietarios = new javax.swing.JMenuItem();
        jMRSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Sistema");

        jMSAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/agenda.png"))); // NOI18N
        jMSAgenda.setText("Agenda");
        jMSAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(jMSAgenda);
        jMenu1.add(jMSSeparator1);

        jMSApartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/building.png"))); // NOI18N
        jMSApartamentos.setText("Apartamentos");
        jMSApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSApartamentosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSApartamentos);
        jMenu1.add(jMSSeparator2);

        jMSAreasLazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/area_lazer.png"))); // NOI18N
        jMSAreasLazer.setText("Areas de Lazer");
        jMSAreasLazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSAreasLazerActionPerformed(evt);
            }
        });
        jMenu1.add(jMSAreasLazer);
        jMenu1.add(jMSSeparator3);

        jMSBlocos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/bloco.png"))); // NOI18N
        jMSBlocos.setText("Blocos");
        jMSBlocos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSBlocosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSBlocos);
        jMenu1.add(jMSSeparator4);

        jMSCorreios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/correios.png"))); // NOI18N
        jMSCorreios.setText("Correios");
        jMSCorreios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMSCorreios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSCorreiosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSCorreios);
        jMenu1.add(jMSSeparator5);

        jMSFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/funcionario.png"))); // NOI18N
        jMSFuncionarios.setText("Funcionários");
        jMSFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSFuncionarios);
        jMenu1.add(jMSSeparator6);

        jMSGaragens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/garage.png"))); // NOI18N
        jMSGaragens.setText("Garagens");
        jMSGaragens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSGaragensActionPerformed(evt);
            }
        });
        jMenu1.add(jMSGaragens);
        jMenu1.add(jMSSeparator7);

        jMSMoradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/morador.png"))); // NOI18N
        jMSMoradores.setText("Moradores");
        jMSMoradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSMoradoresActionPerformed(evt);
            }
        });
        jMenu1.add(jMSMoradores);
        jMenu1.add(jMSSeparator8);

        jMSProprietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/prop.png"))); // NOI18N
        jMSProprietarios.setText("Proprietarios");
        jMSProprietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSProrietariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSProprietarios);
        jMenu1.add(jMSSeparator9);

        jMSServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/servico.png"))); // NOI18N
        jMSServicos.setText("Serviços");
        jMSServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSServicosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSServicos);
        jMenu1.add(jMSSeparator10);

        jMSCarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/car.png"))); // NOI18N
        jMSCarros.setText("Veículos");
        jMSCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSCarrosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSCarros);
        jMenu1.add(jMSSeparator11);

        jMSTorres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/torres.png"))); // NOI18N
        jMSTorres.setText("Torres");
        jMSTorres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSTorresActionPerformed(evt);
            }
        });
        jMenu1.add(jMSTorres);

        jMenuBar1.add(jMenu1);

        jMRApartamento.setText("Relatorios");

        jMRApartamentos.setText("Apartamentos");
        jMRApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRApartamentoActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRApartamentos);
        jMRApartamento.add(jMRSeparator1);

        jMRProprietarios.setText("Proprietarios");
        jMRProprietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRProprietariosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRProprietarios);
        jMRApartamento.add(jMRSeparator2);

        jMenuBar1.add(jMRApartamento);

        jMenu3.setText("Sair");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/exit.png"))); // NOI18N
        jMenuItem7.setText("Sair");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRApartamentoActionPerformed
        try {
            JasperPrint relatorioApartamento = this.gerarRelatorioJasper("apartamento");

            JasperViewer.viewReport(relatorioApartamento, false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuRApartamentoActionPerformed

    private void jMenuSApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSApartamentosActionPerformed
        ViewApartamento viewApartamento = new ViewApartamento(new ModelApartamento(), new DAOApartamentos());

        this._handlerJanela.configurarJanela(viewApartamento);
        this._handlerJanela.rederizarJanela(viewApartamento);
    }//GEN-LAST:event_jMenuSApartamentosActionPerformed

    private void jMSProrietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSProrietariosActionPerformed
        ViewProprietario viewProprietario = new ViewProprietario(new ModelProprietario(), new DAOProprietarios());

        this._handlerJanela.configurarJanela(viewProprietario);
        this._handlerJanela.rederizarJanela(viewProprietario);
    }//GEN-LAST:event_jMSProrietariosActionPerformed

    private void jMenuRProprietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRProprietariosActionPerformed
        try {
            JasperPrint relatorioProprietario = this.gerarRelatorioJasper("propietario");

            JasperViewer.viewReport(relatorioProprietario, false);
        } catch (Exception e) {
        }       
    }//GEN-LAST:event_jMenuRProprietariosActionPerformed

    private void jMSBlocosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSBlocosActionPerformed
        ViewBloco viewBloco = new ViewBloco(new ModelBloco(), new DAOBlocos());

        this._handlerJanela.configurarJanela(viewBloco);
        this._handlerJanela.rederizarJanela(viewBloco);
    }//GEN-LAST:event_jMSBlocosActionPerformed

    private void jMSCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSCarrosActionPerformed
        ViewCarro viewCarro = new ViewCarro(new ModelCarro(), new DAOCarros());

        this._handlerJanela.configurarJanela(viewCarro);
        this._handlerJanela.rederizarJanela(viewCarro);
    }//GEN-LAST:event_jMSCarrosActionPerformed

    private void jMSGaragensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSGaragensActionPerformed
        ViewGaragem viewGaragem = new ViewGaragem(new ModelGaragem(), new DAOGaragens());

        this._handlerJanela.configurarJanela(viewGaragem);
        this._handlerJanela.rederizarJanela(viewGaragem);
    }//GEN-LAST:event_jMSGaragensActionPerformed

    private void jMSAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSAgendaActionPerformed
        ViewAgenda viewAgenda = new ViewAgenda(new ModelAgenda(), new DAOAgendas());

        this._handlerJanela.configurarJanela(viewAgenda);
        this._handlerJanela.rederizarJanela(viewAgenda);
    }//GEN-LAST:event_jMSAgendaActionPerformed

    private void jMSAreasLazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSAreasLazerActionPerformed
        ViewAreaLazer viewAreaLazer = new ViewAreaLazer(new ModelAreaLazer(), new DAOAreasLazer());

        this._handlerJanela.configurarJanela(viewAreaLazer);
        this._handlerJanela.rederizarJanela(viewAreaLazer);
    }//GEN-LAST:event_jMSAreasLazerActionPerformed

    private void jMSCorreiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSCorreiosActionPerformed
        ViewCorreio viewCorreio = new ViewCorreio(new ModelCorreio(), new DAOCorreios());

        this._handlerJanela.configurarJanela(viewCorreio);
        this._handlerJanela.rederizarJanela(viewCorreio);
    }//GEN-LAST:event_jMSCorreiosActionPerformed

    private void jMSFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSFuncionariosActionPerformed
        ViewFuncionario viewFuncionario = new ViewFuncionario(new ModelFuncionario(), new DAOFuncionarios());

        this._handlerJanela.configurarJanela(viewFuncionario);
        this._handlerJanela.rederizarJanela(viewFuncionario);
    }//GEN-LAST:event_jMSFuncionariosActionPerformed

    private void jMSMoradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSMoradoresActionPerformed
        ViewMorador viewMorador = new ViewMorador(new ModelMorador(), new DAOMoradores());

        this._handlerJanela.configurarJanela(viewMorador);
        this._handlerJanela.rederizarJanela(viewMorador);
    }//GEN-LAST:event_jMSMoradoresActionPerformed

    private void jMSServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSServicosActionPerformed
        ViewServico viewServico = new ViewServico(new ModelServico(), new DAOServicos());

        this._handlerJanela.configurarJanela(viewServico);
        this._handlerJanela.rederizarJanela(viewServico);
    }//GEN-LAST:event_jMSServicosActionPerformed

    private void jMSTorresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSTorresActionPerformed
        ViewTorre viewTorre = new ViewTorre(new ModelTorre(), new DAOTorres());

        this._handlerJanela.configurarJanela(viewTorre);
        this._handlerJanela.rederizarJanela(viewTorre);
    }//GEN-LAST:event_jMSTorresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMRApartamento;
    private javax.swing.JMenuItem jMRApartamentos;
    private javax.swing.JMenuItem jMRProprietarios;
    private javax.swing.JPopupMenu.Separator jMRSeparator1;
    private javax.swing.JPopupMenu.Separator jMRSeparator2;
    private javax.swing.JMenuItem jMSAgenda;
    private javax.swing.JMenuItem jMSApartamentos;
    private javax.swing.JMenuItem jMSAreasLazer;
    private javax.swing.JMenuItem jMSBlocos;
    private javax.swing.JMenuItem jMSCarros;
    private javax.swing.JMenuItem jMSCorreios;
    private javax.swing.JMenuItem jMSFuncionarios;
    private javax.swing.JMenuItem jMSGaragens;
    private javax.swing.JMenuItem jMSMoradores;
    private javax.swing.JMenuItem jMSProprietarios;
    private javax.swing.JPopupMenu.Separator jMSSeparator1;
    private javax.swing.JPopupMenu.Separator jMSSeparator10;
    private javax.swing.JPopupMenu.Separator jMSSeparator11;
    private javax.swing.JPopupMenu.Separator jMSSeparator2;
    private javax.swing.JPopupMenu.Separator jMSSeparator3;
    private javax.swing.JPopupMenu.Separator jMSSeparator4;
    private javax.swing.JPopupMenu.Separator jMSSeparator5;
    private javax.swing.JPopupMenu.Separator jMSSeparator6;
    private javax.swing.JPopupMenu.Separator jMSSeparator7;
    private javax.swing.JPopupMenu.Separator jMSSeparator8;
    private javax.swing.JPopupMenu.Separator jMSSeparator9;
    private javax.swing.JMenuItem jMSServicos;
    private javax.swing.JMenuItem jMSTorres;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
