package condominio.views;

import net.sf.jasperreports.engine.JasperPrint;

import common.handlers.HandlerJanela;
import common.handlers.HandlerRelatorio;
import common.enums.EnumRelatorios;
import condominio.models.*;
import condominio.daos.*;

/**
 *
 * @author Marcelo
 */
public class ViewHome extends javax.swing.JFrame {
    public ViewHome(
        HandlerJanela injectedHandlerJanela,
        HandlerRelatorio injtectedHandlerRelatorio
    ) {
        this._HANDLER_JANELA = injectedHandlerJanela;
        this._HANDLER_RELATORIO = injtectedHandlerRelatorio;

        initComponents();
    }

    private final HandlerJanela _HANDLER_JANELA;
    private final HandlerRelatorio _HANDLER_RELATORIO;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMSAgenda = new javax.swing.JMenuItem();
        jMSSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMSApartamentos = new javax.swing.JMenuItem();
        jMSSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMSAreasLazer = new javax.swing.JMenuItem();
        jMSSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMSBlocos = new javax.swing.JMenuItem();
        jMSSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMSCorreios = new javax.swing.JMenuItem();
        jMSSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMSFuncionarios = new javax.swing.JMenuItem();
        jMSSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMSGaragens = new javax.swing.JMenuItem();
        jMSSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMSMoradores = new javax.swing.JMenuItem();
        jMSSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMSProprietarios = new javax.swing.JMenuItem();
        jMSSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMSServicos = new javax.swing.JMenuItem();
        jMSSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMSCarros = new javax.swing.JMenuItem();
        jMSSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMSTorres = new javax.swing.JMenuItem();
        jMRApartamento = new javax.swing.JMenu();
        jMRAgendas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMRApartamentos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMRAreasLazer = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMRBlocos = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMRCorreios = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMRFuncionarios = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMRGaragens = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMRMoradores = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMRProprietarios = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMRServicos = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMRVeiculos = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMRTorres = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Sistema");

        jMSAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/agenda.png"))); // NOI18N
        jMSAgenda.setText("Agenda");
        jMSAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(jMSAgenda);
        jMenu1.add(jMSSeparator1);

        jMSApartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/building.png"))); // NOI18N
        jMSApartamentos.setText("Apartamentos");
        jMSApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSApartamentosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSApartamentos);
        jMenu1.add(jMSSeparator2);

        jMSAreasLazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/area_lazer.png"))); // NOI18N
        jMSAreasLazer.setText("Areas de Lazer");
        jMSAreasLazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSAreasLazerActionPerformed(evt);
            }
        });
        jMenu1.add(jMSAreasLazer);
        jMenu1.add(jMSSeparator3);

        jMSBlocos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/bloco.png"))); // NOI18N
        jMSBlocos.setText("Blocos");
        jMSBlocos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSBlocosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSBlocos);
        jMenu1.add(jMSSeparator4);

        jMSCorreios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/correios.png"))); // NOI18N
        jMSCorreios.setText("Correios");
        jMSCorreios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMSCorreios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSCorreiosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSCorreios);
        jMenu1.add(jMSSeparator5);

        jMSFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/funcionario.png"))); // NOI18N
        jMSFuncionarios.setText("Funcionários");
        jMSFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSFuncionarios);
        jMenu1.add(jMSSeparator6);

        jMSGaragens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/garage.png"))); // NOI18N
        jMSGaragens.setText("Garagens");
        jMSGaragens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSGaragensActionPerformed(evt);
            }
        });
        jMenu1.add(jMSGaragens);
        jMenu1.add(jMSSeparator7);

        jMSMoradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/morador.png"))); // NOI18N
        jMSMoradores.setText("Moradores");
        jMSMoradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSMoradoresActionPerformed(evt);
            }
        });
        jMenu1.add(jMSMoradores);
        jMenu1.add(jMSSeparator8);

        jMSProprietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/prop.png"))); // NOI18N
        jMSProprietarios.setText("Proprietarios");
        jMSProprietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSProrietariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSProprietarios);
        jMenu1.add(jMSSeparator9);

        jMSServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/servico.png"))); // NOI18N
        jMSServicos.setText("Serviços");
        jMSServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSServicosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSServicos);
        jMenu1.add(jMSSeparator10);

        jMSCarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/car.png"))); // NOI18N
        jMSCarros.setText("Veículos");
        jMSCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSCarrosActionPerformed(evt);
            }
        });
        jMenu1.add(jMSCarros);
        jMenu1.add(jMSSeparator11);

        jMSTorres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/torres.png"))); // NOI18N
        jMSTorres.setText("Torres");
        jMSTorres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSTorresActionPerformed(evt);
            }
        });
        jMenu1.add(jMSTorres);

        jMenuBar1.add(jMenu1);

        jMRApartamento.setText("Relatorios");

        jMRAgendas.setText("Agendas");
        jMRAgendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRAgendasActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRAgendas);
        jMRApartamento.add(jSeparator1);

        jMRApartamentos.setText("Apartamentos");
        jMRApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRApartamentosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRApartamentos);
        jMRApartamento.add(jSeparator2);

        jMRAreasLazer.setText("Areas de Lazer");
        jMRAreasLazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRAreasLazerActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRAreasLazer);
        jMRApartamento.add(jSeparator3);

        jMRBlocos.setText("Blocos");
        jMRBlocos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRBlocosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRBlocos);
        jMRApartamento.add(jSeparator4);

        jMRCorreios.setText("Correios");
        jMRCorreios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRCorreiosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRCorreios);
        jMRApartamento.add(jSeparator5);

        jMRFuncionarios.setText("Funcionários");
        jMRFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRFuncionariosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRFuncionarios);
        jMRApartamento.add(jSeparator6);

        jMRGaragens.setText("Garagens");
        jMRGaragens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRGaragensActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRGaragens);
        jMRApartamento.add(jSeparator7);

        jMRMoradores.setText("Moradores");
        jMRMoradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRMoradoresActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRMoradores);
        jMRApartamento.add(jSeparator8);

        jMRProprietarios.setText("Proprietarios");
        jMRProprietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRProprietariosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRProprietarios);
        jMRApartamento.add(jSeparator9);

        jMRServicos.setText("Serviços");
        jMRServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRServicosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRServicos);
        jMRApartamento.add(jSeparator10);

        jMRVeiculos.setText("Veículos");
        jMRVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRVeiculosActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRVeiculos);
        jMRApartamento.add(jSeparator11);

        jMRTorres.setText("Torres");
        jMRTorres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRTorresActionPerformed(evt);
            }
        });
        jMRApartamento.add(jMRTorres);

        jMenuBar1.add(jMRApartamento);

        jMenu3.setText("Sair");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view/icons/exit.png"))); // NOI18N
        jMenuItem7.setText("Sair");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSApartamentosActionPerformed
        ViewApartamento viewApartamento = new ViewApartamento(
            this._HANDLER_JANELA,
            new ModelApartamento(),
            new DAOApartamentos()
        );

        this._HANDLER_JANELA.configurarJanela(viewApartamento);
        this._HANDLER_JANELA.rederizarJanela(viewApartamento);
    }//GEN-LAST:event_jMenuSApartamentosActionPerformed

    private void jMSProrietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSProrietariosActionPerformed
        ViewProprietario viewProprietario = new ViewProprietario(
            this._HANDLER_JANELA,
            new ModelProprietario(),
            new DAOProprietarios()
        );

        this._HANDLER_JANELA.configurarJanela(viewProprietario);
        this._HANDLER_JANELA.rederizarJanela(viewProprietario);
    }//GEN-LAST:event_jMSProrietariosActionPerformed

    private void jMSBlocosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSBlocosActionPerformed
        ViewBloco viewBloco = new ViewBloco(
            this._HANDLER_JANELA,
            new ModelBloco(),
            new DAOBlocos()
        );

        this._HANDLER_JANELA.configurarJanela(viewBloco);
        this._HANDLER_JANELA.rederizarJanela(viewBloco);
    }//GEN-LAST:event_jMSBlocosActionPerformed

    private void jMSCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSCarrosActionPerformed
        ViewCarro viewCarro = new ViewCarro(
            this._HANDLER_JANELA,
            new ModelCarro(),
            new DAOCarros()
        );

        this._HANDLER_JANELA.configurarJanela(viewCarro);
        this._HANDLER_JANELA.rederizarJanela(viewCarro);
    }//GEN-LAST:event_jMSCarrosActionPerformed

    private void jMSGaragensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSGaragensActionPerformed
        ViewGaragem viewGaragem = new ViewGaragem(
            this._HANDLER_JANELA,
            new ModelGaragem(),
            new DAOGaragens()
        );

        this._HANDLER_JANELA.configurarJanela(viewGaragem);
        this._HANDLER_JANELA.rederizarJanela(viewGaragem);
    }//GEN-LAST:event_jMSGaragensActionPerformed

    private void jMSAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSAgendaActionPerformed
        ViewAgenda viewAgenda = new ViewAgenda(
            this._HANDLER_JANELA,
            new ModelAgenda(),
            new DAOAgendas()
        );

        this._HANDLER_JANELA.configurarJanela(viewAgenda);
        this._HANDLER_JANELA.rederizarJanela(viewAgenda);
    }//GEN-LAST:event_jMSAgendaActionPerformed

    private void jMSAreasLazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSAreasLazerActionPerformed
        ViewAreaLazer viewAreaLazer = new ViewAreaLazer(
            this._HANDLER_JANELA,
            new ModelAreaLazer(),
            new DAOAreasLazer()
        );

        this._HANDLER_JANELA.configurarJanela(viewAreaLazer);
        this._HANDLER_JANELA.rederizarJanela(viewAreaLazer);
    }//GEN-LAST:event_jMSAreasLazerActionPerformed

    private void jMSCorreiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSCorreiosActionPerformed
        ViewCorreio viewCorreio = new ViewCorreio(
            this._HANDLER_JANELA,
            new ModelCorreio(),
            new DAOCorreios()
        );

        this._HANDLER_JANELA.configurarJanela(viewCorreio);
        this._HANDLER_JANELA.rederizarJanela(viewCorreio);
    }//GEN-LAST:event_jMSCorreiosActionPerformed

    private void jMSFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSFuncionariosActionPerformed
        ViewFuncionario viewFuncionario = new ViewFuncionario(
            this._HANDLER_JANELA,
            new ModelFuncionario(),
            new DAOFuncionarios()
        );

        this._HANDLER_JANELA.configurarJanela(viewFuncionario);
        this._HANDLER_JANELA.rederizarJanela(viewFuncionario);
    }//GEN-LAST:event_jMSFuncionariosActionPerformed

    private void jMSMoradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSMoradoresActionPerformed
        ViewMorador viewMorador = new ViewMorador(
            this._HANDLER_JANELA,
            new ModelMorador(),
            new DAOMoradores()
        );

        this._HANDLER_JANELA.configurarJanela(viewMorador);
        this._HANDLER_JANELA.rederizarJanela(viewMorador);
    }//GEN-LAST:event_jMSMoradoresActionPerformed

    private void jMSServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSServicosActionPerformed
        ViewServico viewServico = new ViewServico(
            this._HANDLER_JANELA,
            new ModelServico(),
            new DAOServicos()
        );

        this._HANDLER_JANELA.configurarJanela(viewServico);
        this._HANDLER_JANELA.rederizarJanela(viewServico);
    }//GEN-LAST:event_jMSServicosActionPerformed

    private void jMSTorresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSTorresActionPerformed
        ViewTorre viewTorre = new ViewTorre(
            this._HANDLER_JANELA,
            new ModelTorre(),
            new DAOTorres()
        );

        this._HANDLER_JANELA.configurarJanela(viewTorre);
        this._HANDLER_JANELA.rederizarJanela(viewTorre);
    }//GEN-LAST:event_jMSTorresActionPerformed

    private void jMRAgendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRAgendasActionPerformed
        JasperPrint relatorioAgenda = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_AGENDA.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioAgenda);
    }//GEN-LAST:event_jMRAgendasActionPerformed

    private void jMRApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRApartamentosActionPerformed
        JasperPrint relatorioApartamento = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_APARTAMENTO.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioApartamento);
    }//GEN-LAST:event_jMRApartamentosActionPerformed

    private void jMRAreasLazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRAreasLazerActionPerformed
        JasperPrint relatorioAreaLazer = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_AREA_LAZER.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioAreaLazer);
    }//GEN-LAST:event_jMRAreasLazerActionPerformed

    private void jMRBlocosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRBlocosActionPerformed
        JasperPrint relatorioBloco = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_BLOCO.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioBloco);
    }//GEN-LAST:event_jMRBlocosActionPerformed

    private void jMRCorreiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRCorreiosActionPerformed
        JasperPrint relatorioCorreio = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_CORREIO.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioCorreio);
    }//GEN-LAST:event_jMRCorreiosActionPerformed

    private void jMRFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRFuncionariosActionPerformed
        JasperPrint relatorioFuncionario = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_FUNCIONARIO.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioFuncionario);
    }//GEN-LAST:event_jMRFuncionariosActionPerformed

    private void jMRGaragensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRGaragensActionPerformed
        JasperPrint relatorioGaragem = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_GARAGEM.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioGaragem);
    }//GEN-LAST:event_jMRGaragensActionPerformed

    private void jMRMoradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRMoradoresActionPerformed
        JasperPrint relatorioMorador = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_MORADOR.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioMorador);
    }//GEN-LAST:event_jMRMoradoresActionPerformed

    private void jMRProprietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRProprietariosActionPerformed
        JasperPrint relatorioRelatorio = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_PROPRIETARIO.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioRelatorio);
    }//GEN-LAST:event_jMRProprietariosActionPerformed

    private void jMRServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRServicosActionPerformed
        JasperPrint relatorioServico = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_SERVICO.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioServico);
    }//GEN-LAST:event_jMRServicosActionPerformed

    private void jMRVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRVeiculosActionPerformed
        JasperPrint relatorioVeiculo = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_VEICULO.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioVeiculo);
    }//GEN-LAST:event_jMRVeiculosActionPerformed

    private void jMRTorresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRTorresActionPerformed
        JasperPrint relatorioTorre = this._HANDLER_RELATORIO.gerarRelatorioJasper(EnumRelatorios.RELATORIO_TORRE.getNomeTipoCampo());

        this._HANDLER_RELATORIO.renderizarRelatorio(relatorioTorre);
    }//GEN-LAST:event_jMRTorresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMRAgendas;
    private javax.swing.JMenu jMRApartamento;
    private javax.swing.JMenuItem jMRApartamentos;
    private javax.swing.JMenuItem jMRAreasLazer;
    private javax.swing.JMenuItem jMRBlocos;
    private javax.swing.JMenuItem jMRCorreios;
    private javax.swing.JMenuItem jMRFuncionarios;
    private javax.swing.JMenuItem jMRGaragens;
    private javax.swing.JMenuItem jMRMoradores;
    private javax.swing.JMenuItem jMRProprietarios;
    private javax.swing.JMenuItem jMRServicos;
    private javax.swing.JMenuItem jMRTorres;
    private javax.swing.JMenuItem jMRVeiculos;
    private javax.swing.JMenuItem jMSAgenda;
    private javax.swing.JMenuItem jMSApartamentos;
    private javax.swing.JMenuItem jMSAreasLazer;
    private javax.swing.JMenuItem jMSBlocos;
    private javax.swing.JMenuItem jMSCarros;
    private javax.swing.JMenuItem jMSCorreios;
    private javax.swing.JMenuItem jMSFuncionarios;
    private javax.swing.JMenuItem jMSGaragens;
    private javax.swing.JMenuItem jMSMoradores;
    private javax.swing.JMenuItem jMSProprietarios;
    private javax.swing.JPopupMenu.Separator jMSSeparator1;
    private javax.swing.JPopupMenu.Separator jMSSeparator10;
    private javax.swing.JPopupMenu.Separator jMSSeparator11;
    private javax.swing.JPopupMenu.Separator jMSSeparator2;
    private javax.swing.JPopupMenu.Separator jMSSeparator3;
    private javax.swing.JPopupMenu.Separator jMSSeparator4;
    private javax.swing.JPopupMenu.Separator jMSSeparator5;
    private javax.swing.JPopupMenu.Separator jMSSeparator6;
    private javax.swing.JPopupMenu.Separator jMSSeparator7;
    private javax.swing.JPopupMenu.Separator jMSSeparator8;
    private javax.swing.JPopupMenu.Separator jMSSeparator9;
    private javax.swing.JMenuItem jMSServicos;
    private javax.swing.JMenuItem jMSTorres;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
